SapphireVillage_PlayerHouse_Bathroom_MapScripts::
	.byte 0


SapphireVillage_PlayerHouse_Bathroom_Toilet::
# 4 "data/maps/SapphireVillage_PlayerHouse_Bathroom/scripts.pory"
	msgbox SapphireVillage_PlayerHouse_Bathroom_Toilet_Text_0
# 5 "data/maps/SapphireVillage_PlayerHouse_Bathroom/scripts.pory"
	release
	return


SapphireVillage_PlayerHouse_Bathroom_Sink::
# 9 "data/maps/SapphireVillage_PlayerHouse_Bathroom/scripts.pory"
	msgbox SapphireVillage_PlayerHouse_Bathroom_Sink_Text_0
# 10 "data/maps/SapphireVillage_PlayerHouse_Bathroom/scripts.pory"
	release
	return


SapphireVillage_PlayerHouse_Bathtub::
# 14 "data/maps/SapphireVillage_PlayerHouse_Bathroom/scripts.pory"
	msgbox SapphireVillage_PlayerHouse_Bathtub_Text_0
# 15 "data/maps/SapphireVillage_PlayerHouse_Bathroom/scripts.pory"
	release
	return


SapphireVillage_PlayerHouse_Bathroom_Toilet_Text_0:
# 4 "data/maps/SapphireVillage_PlayerHouse_Bathroom/scripts.pory"
	.string "Remember the time I found a Rage\nCandy Bar in the toilet?$"

SapphireVillage_PlayerHouse_Bathroom_Sink_Text_0:
# 9 "data/maps/SapphireVillage_PlayerHouse_Bathroom/scripts.pory"
	.string "Can't forget to wash my hands!$"

SapphireVillage_PlayerHouse_Bathtub_Text_0:
# 14 "data/maps/SapphireVillage_PlayerHouse_Bathroom/scripts.pory"
	.string "Would it kill these people to install\na shower curtain?$"
