SapphireVillage_PlayerHouse_MomRoom_MapScripts::
	.byte 0


SapphireVillage_PlayerHouse_MomRoom_Mudkip::
# 4 "data/maps/SapphireVillage_PlayerHouse_MomRoom/scripts.pory"
	msgbox SapphireVillage_PlayerHouse_MomRoom_Mudkip_Text_0
# 5 "data/maps/SapphireVillage_PlayerHouse_MomRoom/scripts.pory"
	release
	return


SapphireVillage_PlayerHouse_MomRoom_PC::
# 9 "data/maps/SapphireVillage_PlayerHouse_MomRoom/scripts.pory"
	msgbox SapphireVillage_PlayerHouse_MomRoom_PC_Text_0
# 10 "data/maps/SapphireVillage_PlayerHouse_MomRoom/scripts.pory"
	release
	return


SapphireVillage_PlayerHouse_MomRoom_Mudkip_Text_0:
# 4 "data/maps/SapphireVillage_PlayerHouse_MomRoom/scripts.pory"
	.string "So I herd Mom lieks Mudkipz.$"

SapphireVillage_PlayerHouse_MomRoom_PC_Text_0:
# 9 "data/maps/SapphireVillage_PlayerHouse_MomRoom/scripts.pory"
	.string "Mom should really learn to lock her\ncomputer when she isn't using it…$"
