#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(POWER_UP_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(VENOSHOCK) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(PLAY_ROUGH) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(FLAME_CHARGE) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(VOLT_SWITCH) \
    F(CURSE) \
    F(BREAKING_SWIPE) \
    F(ROOST) \
    F(FOCUS_BLAST) \
    F(ENERGY_BALL) \
    F(FALSE_SWIPE) \
    F(SCALD) \
    F(U_TURN) \
    F(CHARGE_BEAM) \
    F(DRAGON_PULSE) \
    F(ZEN_HEADBUTT) \
    F(MUD_SHOT) \
    F(WILL_O_WISP) \
    F(ACROBATICS) \
    F(POWER_GEM) \
    F(EXPLOSION) \
    F(SHADOW_CLAW) \
    F(PAYBACK) \
    F(FLIP_TURN) \
    F(GIGA_IMPACT) \
    F(SEED_BOMB) \
    F(FLASH) \
    F(STONE_EDGE) \
    F(AVALANCHE) \
    F(THUNDER_WAVE) \
    F(GYRO_BALL) \
    F(SWORDS_DANCE) \
    F(STRUGGLE_BUG) \
    F(HEX) \
    F(BULLDOZE) \
    F(DARK_PULSE) \
    F(ROCK_SLIDE) \
    F(X_SCISSOR) \
    F(DRAGON_TAIL) \
    F(NASTY_PLOT) \
    F(POISON_JAB) \
    F(DEFOG) \
    F(PHANTOM_FORCE) \
    F(DRAINING_KISS) \
    F(PLUCK) \
    F(RAZOR_SHELL) \
    F(SUBSTITUTE) \
    F(FLASH_CANNON) \
    F(AIR_SLASH) \
    F(WILD_CHARGE) \
    F(EARTH_POWER) \
    F(SNARL) \
    F(BUG_BUZZ) \
    F(IRON_HEAD) \
    F(LIQUIDATION) \
    F(DAZZLING_GLEAM) \
    F(SCALE_SHOT) \

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(ROCK_CLIMB) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
