gText_Birch_Welcome::
	.string "Oh, hey... It's you...\n"
	.string "What is it that ya want, kid?\p"
	.string "Oh, right. The intro sequence.\n"
	.string "This is the Pokémon world, I guess?\p"
	.string "I'm Professor Allen Aspen.\n"
	.string "Don't wear it out...\p"
	.string "We both live in a dead-end hole\n"
	.string "called Sapphire Village.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This world is inhabited by them.\n"
	.string "Shocker, right?”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "I'd say they're pretty good for\n"
	.string "making money, I guess...\p"
	.string "As for myself...\n"
	.string "I study 'em.\p"
	.string "I chose the wrong major in college,\n"
	.string "now that I'm lookin' back...\p"
	.string "Anyway, you don't care about me.\n"
	.string "What about you?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "What's your story?$"

gText_Birch_BoyOrGirl::
	.string "Which twin were you again?\n"
	.string "The dude or the chick?$"

gText_Birch_WhatsYourName::
	.string "Right, right, I think I remember now.\n"
	.string "Uhh, wait, what was your name again?$"

gText_Birch_SoItsPlayer::
	.string "So your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}!\p"
	.string "Your journey's about to start!\n"
	.string "Meet me in my Lab tomorrow.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Your Mom forced me to get you a-\p"
	.string "Er, I meant to say I have something\n"
	.string "nice waiting for ya.\p"
	.string "So hurry up and get some sleep already\n"
	.string "so we can get this over with.\p"
	.string "Remember!\n"
	.string "My Lab tomorrow. See ya then.\p"
	.string "$"
