gText_ObtainedTheItem::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} obtained the {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "The Bag is full…$"

gText_PutItemInPocket::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} Pocket.$"

gText_PlayerFoundOneItem::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} found one {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The Bag is full…$"

gText_PlayerPutItemInBag::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} put away the {STR_VAR_2}\n"
	.string "in the Bag.$"

gText_ObtainedTheDecor::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} obtained {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} found {STR_VAR_1} {STR_VAR_2}!$"
