SapphireVillage_PlayerHouse_AlexRoom_MapScripts::
	.byte 0


SapphireVillage_PlayerHouse_AlexRoom_PC::
# 4 "data/maps/SapphireVillage_PlayerHouse_AlexRoom/scripts.pory"
	msgbox SapphireVillage_PlayerHouse_AlexRoom_PC_Text_0
# 5 "data/maps/SapphireVillage_PlayerHouse_AlexRoom/scripts.pory"
	release
	return


SapphireVillage_PlayerHouse_AlexRoom_Bookshelf::
# 9 "data/maps/SapphireVillage_PlayerHouse_AlexRoom/scripts.pory"
	msgbox SapphireVillage_PlayerHouse_AlexRoom_Bookshelf_Text_0
# 10 "data/maps/SapphireVillage_PlayerHouse_AlexRoom/scripts.pory"
	release
	return


SapphireVillage_PlayerHouse_AlexRoom_Game::
# 14 "data/maps/SapphireVillage_PlayerHouse_AlexRoom/scripts.pory"
	msgbox SapphireVillage_PlayerHouse_AlexRoom_Game_Text_0
# 15 "data/maps/SapphireVillage_PlayerHouse_AlexRoom/scripts.pory"
	release
	return


SapphireVillage_PlayerHouse_AlexRoom_PC_Text_0:
# 4 "data/maps/SapphireVillage_PlayerHouse_AlexRoom/scripts.pory"
	.string "Huh? What's e62-\nOh, it's that site Alex keeps visiting…$"

SapphireVillage_PlayerHouse_AlexRoom_Bookshelf_Text_0:
# 9 "data/maps/SapphireVillage_PlayerHouse_AlexRoom/scripts.pory"
	.string "A collection of manga lines the shelves.\nMonster Musume? Peak fiction.$"

SapphireVillage_PlayerHouse_AlexRoom_Game_Text_0:
# 14 "data/maps/SapphireVillage_PlayerHouse_AlexRoom/scripts.pory"
	.string "An NES Classic Mini.\nLots of good games on here.$"
