Common_EventScript_SetGymTrainers::
	switch VAR_0x8008
	case 1, RustboroCity_Gym_SetGymTrainers
	case 2, DewfordTown_Gym_SetGymTrainers
	case 3, MauvilleCity_Gym_SetGymTrainers
	case 4, LavaridgeTown_Gym_SetGymTrainers
	case 5, PetalburgCity_Gym_SetGymTrainers
	case 6, FortreeCity_Gym_SetGymTrainers
	case 7, MossdeepCity_Gym_SetGymTrainers
	case 8, SootopolisCity_Gym_SetGymTrainers
	end

RustboroCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_320
	settrainerflag TRAINER_321
	settrainerflag TRAINER_571
	return

DewfordTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_179
	settrainerflag TRAINER_425
	settrainerflag TRAINER_426
	settrainerflag TRAINER_572
	settrainerflag TRAINER_574
	settrainerflag TRAINER_573
	return

MauvilleCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_191
	settrainerflag TRAINER_194
	settrainerflag TRAINER_323
	settrainerflag TRAINER_649
	settrainerflag TRAINER_802
	return

LavaridgeTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_201
	settrainerflag TRAINER_203
	settrainerflag TRAINER_205
	settrainerflag TRAINER_648
	settrainerflag TRAINER_650
	settrainerflag TRAINER_204
	settrainerflag TRAINER_202
	settrainerflag TRAINER_501
	return

PetalburgCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_71
	settrainerflag TRAINER_72
	settrainerflag TRAINER_73
	settrainerflag TRAINER_74
	settrainerflag TRAINER_89
	settrainerflag TRAINER_90
	settrainerflag TRAINER_91
	return

FortreeCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_401
	settrainerflag TRAINER_654
	settrainerflag TRAINER_655
	settrainerflag TRAINER_404
	settrainerflag TRAINER_402
	settrainerflag TRAINER_803
	return

MossdeepCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_233
	settrainerflag TRAINER_234
	settrainerflag TRAINER_235
	settrainerflag TRAINER_244
	settrainerflag TRAINER_245
	settrainerflag TRAINER_246
	settrainerflag TRAINER_575
	settrainerflag TRAINER_582
	settrainerflag TRAINER_583
	settrainerflag TRAINER_584
	settrainerflag TRAINER_591
	settrainerflag TRAINER_585
	return

SootopolisCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_613
	settrainerflag TRAINER_614
	settrainerflag TRAINER_118
	settrainerflag TRAINER_128
	settrainerflag TRAINER_129
	settrainerflag TRAINER_130
	settrainerflag TRAINER_131
	settrainerflag TRAINER_301
	settrainerflag TRAINER_502
	settrainerflag TRAINER_115
	return
